name: rpgnamegenerator
description: A dart generator of names for characters in role play games, three races (elfs, orcs and humans) and two gender (masculine and femenie)
version: 1.0.1
homepage: https://github.com/TarugasTrungland/rpg-name-generator
author: tarugastrungland <tarugastrungland@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
