name: rpgnamegenerator
description: A dart generator of names for characters in role play games
version: 1.0.0
homepage: https://github.com/TarugasTrungland/rpg-name-generator
author: tarugastrungland <tarugastrungland@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
